#!/bin/bash
# programm output sysinfo
TITLE="Ricardo Milos For $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Gerated $CURRENT_TIME, by $USER"

cat << _EOF_
<HTML>
		<HEAD>
			<TITTLE>$TITLE</TITLE>
		</HEAD>
		<BODY>
			<H1>$TITLE</H1>
			<P>$TIME_STAMP</P>
		</BODY>
</HTML>"
_EOF_
